Practice query builder and fix routes
st-huyngo/laravel-intern-2111 pull request #2
Opened 2021-12-21 13:34 UTC by st-huyngo

2021-12-22 03:03 UTC, st-minhdao requested changes
Please check my comment

2021-12-22 03:03 UTC, st-minhdao commented on example-app/app/Http/Controllers/TaskController.php
> +        $due_date = $request->due_date;
tạo ra mấy biến này để làm gì vậy em, mình có thể thêm thẳng vào như ở dưới em làm mà hè

2021-12-22 03:03 UTC, st-minhdao commented on example-app/app/Http/Controllers/TaskController.php
> +        $due_date = $request->due_date;
tương tự :)))

2021-12-22 03:03 UTC, st-minhdao commented on example-app/app/Http/Controllers/TaskController.php
> +        return redirect('/tasks')->with('message', 'Delete Successfully');
dùng redirect()->route()....

2021-12-22 03:03 UTC, st-minhdao commented on example-app/app/Models/Task.php
> +    protected $fillable=['title','description','type','status','start_date','due_date','assignee','estimate','actual'];
cách dòng ra em
thêm khoảng trắng vào sau những dấu phẩy nữa nha

2021-12-22 03:03 UTC, st-minhdao commented on example-app/database/migrations/2021_12_21_082535_create_tasks_table.php
> +            $table->unsignedInteger('type')->nullable(false);
cái ni dùng tinyInt cũng dc rồi

2021-12-22 03:03 UTC, st-minhdao commented on example-app/routes/web.php
> +});
thêm space vào :)))

2021-12-22 04:48 UTC, st-trampham commented on example-app/resources/views/admin/task/edit.blade.php
> +                            <form class="user" action="{{route('tasks.update',['task'=>$task->id])}}" method="POST">
Thêm space, check lại những chỗ khác luôn

2021-12-22 04:52 UTC, st-trampham commented on example-app/resources/views/admin/task/edit.blade.php
>                                      <input type="text" name="assignee" class="form-control form-control-user"
Chỗ này dùng select tag để chọn user chứ nhỉ

2021-12-23 01:36 UTC, st-trampham commented on example-app/app/Http/Controllers/TaskController.php
> +            'assignee' => $request->input('assignee'),
dùng `$request-> assignee` luôn cho đồng bộ em

2021-12-23 01:37 UTC, st-trampham commented on example-app/app/Http/Controllers/TaskController.php
> +            'assignee' => $request->input('assignee'),
tương tự

2021-12-23 01:40 UTC, st-trampham commented on example-app/resources/views/admin/task/create.blade.php
> +                                        <option value="0" selected disabled hidden>Choose Assignee</option>
Chỗ này để `value=""`
Sửa luôn ở view edit task

2021-12-23 12:16 UTC, st-minhdao approved these changes
LGTM

2021-12-23 12:16 UTC, merged